NaturalScience.initDisplay()
NaturalScience.setK(2.68)
basic.forever(function () {
    NaturalScience.setLed(NaturalScience.STM32_LED_STATUS.ON)
    NaturalScience.showUserNumber(0, NaturalScience.TemperatureNumber())
    NaturalScience.showUserText(1, NaturalScience.readBME280Data(NaturalScience.BME280Data.Pressure))
    NaturalScience.showUserText(2, NaturalScience.readBME280Data(NaturalScience.BME280Data.Temperature))
    NaturalScience.showUserText(3, NaturalScience.readBME280Data(NaturalScience.BME280Data.Humidity))
    NaturalScience.showUserText(4, NaturalScience.getK())
    NaturalScience.showUserNumber(5, NaturalScience.getTDS())
    NaturalScience.showUserNumber(6, NaturalScience.getNoise())
    NaturalScience.showUserNumber(7, NaturalScience.getRed())
    basic.pause(2000)
    NaturalScience.clear()
    basic.pause(1000)
    NaturalScience.showUserNumber(0, NaturalScience.getGreen())
    NaturalScience.showUserNumber(1, NaturalScience.getBlue())
    NaturalScience.showUserNumber(2, NaturalScience.getC())
    NaturalScience.showUserText(3, "DFRobot")
    NaturalScience.showUserNumber(4, 2019)
    NaturalScience.setLed(NaturalScience.STM32_LED_STATUS.ON)
    basic.pause(2000)
    NaturalScience.clear()
    NaturalScience.setLed(NaturalScience.STM32_LED_STATUS.OFF)
    basic.pause(500)
    music.playTone(262, music.beat(BeatFraction.Whole))
    basic.pause(2000)
})
